profiles:
  incident_profile:
    columns:
      - key: "id"
        column: "IncidentID"
      - key: "state"
        column: "State"
      - key: ""
        column: "Description"
        regex: "Description"
      - key: ""
        column: "Location"
        regex: "Location"
      - key: ""
        column: "Address"
        regex: "Address"
      - key: ""
        column: "ProductName"
        regex: "Product Name"
      - key: ""
        column: "ConfigurationItem"
        regex: "Configuration Item"
      - key: ""
        column: "IPAddress"
        regex: "IP Address"
      - key: "created_at"
        column: "CreatedAt"
      - key: "updated_at"
        column: "UpdatedAt"
    output_file: "incident_report.csv"
    parse_body: "body.content"
    content_type: "html"

newline_handling: "replace"
newline_replacement: " "
null_value_handling: "empty"
