profiles:
  incident_profile:
    columns:
      - key: ""
        column: "Location"
        regex: "Location"
    output_file: "incident_report.csv"
    parse_body: "body.content"
    content_type: "html"

newline_handling: "replace"
newline_replacement: " "
null_value_handling: "empty"
