profiles:
  test:
    columns:
      - key: "id"
        column: "ID"
      - key: "createdDateTime"
        column: "作成日時"
      - key: "subject"
        column: "件名"
      - key: ""
        column: "説明"
        regex: "Description"
      - key: ""
        column: "場所"
        regex: "Location"
      - key: ""
        column: "住所"
        regex: "Address"
        exact_match: true
      - key: ""
        column: "製品名"
        regex: "Product Name"
      - key: ""
        column: "設定項目"
        regex: "Configuration Item"
      - key: ""
        column: "IPアドレス"
        regex: "IP Address"
        exact_match: true
      - key: "lastModifiedDateTime"
        column: "最終更新日時"
    output_file: "incident_report.csv"
    parse_body: "body.content"
    content_type: "html"

newline_handling: "replace"
newline_replacement: " "
null_value_handling: "empty"
